CREATE TABLE FILMVEDIZI (
	DF_ID SERIAL PRIMARY KEY NOT NULL,
	TUR VARCHAR(500) NOT NULL,
	ADI VARCHAR(500) NOT NULL,
	KONUSU VARCHAR(500) NOT NULL,
	KATEGORISI VARCHAR(500) NOT NULL,
	YONETMEN_ADI VARCHAR(500) NOT NULL,
	OYUNCULAR VARCHAR(500) NOT NULL,
	VIZYONTREND BOOLEAN NOT NULL
);
CREATE TABLE KULLANICILAR (
	KULLANICI_ID SERIAL PRIMARY KEY NOT NULL,
	DF_ID SERIAL REFERENCES FILMVEDIZI (DF_ID),
	EMAIL VARCHAR NOT NULL,
	KULLANICIADI VARCHAR NOT NULL,
	ŞIFRE VARCHAR NOT NULL
);

CREATE TABLE YORUM (
	KULLANICI_ID SERIAL REFERENCES KULLANICILAR (KULLANICI_ID),
	DF_ID SERIAL REFERENCES FILMVEDIZI (DF_ID),
	YORUM TEXT
);

CREATE TABLE KITAPLIK (
	KULLANICI_ID SERIAL REFERENCES KULLANICILAR (KULLANICI_ID),
	DF_ID SERIAL REFERENCES FILMVEDIZI (DF_ID)
);

CREATE TABLE IMDB (
	DF_ID SERIAL REFERENCES FILMVEDIZI (DF_ID),
	IMDBPUAN FLOAT NOT NULL
);

CREATE TABLE TRENDDEKILER (DF_ID SERIAL REFERENCES FILMVEDIZI (DF_ID));

CREATE TABLE VIZYONDAKILER (DF_ID SERIAL REFERENCES FILMVEDIZI (DF_ID));

CREATE TABLE PLATFORM (
	DF_ID SERIAL REFERENCES FILMVEDIZI (DF_ID),
	PLATFORMISMI VARCHAR
);

CREATE TABLE ADMIN (
	ADMIN_ID SERIAL PRIMARY KEY NOT NULL,
	ADMINUSERNAME VARCHAR,
	ADAMINSIFRE VARCHAR,
	ADMINEMAIL VARCHAR
);

CREATE TABLE MESAJLAR (
	ADMIN_ID SERIAL REFERENCES ADMIN (ADMIN_ID),
	KULLANICI_ID SERIAL REFERENCES KULLANICILAR (KULLANICI_ID),
	MESAJ TEXT
);

CREATE TABLE İLETIŞIM (
	ADMIN_ID SERIAL REFERENCES ADMIN (ADMIN_ID),
	TELEFONNO NUMERIC(12),
	INSTAGRAM VARCHAR,
	FACEBOOK VARCHAR,
	TWITTER VARCHAR,
	LOKASYON VARCHAR
);